### PR TITLE
Some major cleanup and restructuring of mongoid_geo

### PR DESCRIPTION
**Pull request by salbito**
Hey guys. I spent the last day just cleaning up mongoid_geo and fixing something here and there. Here is the short list of changes.
- Users can now create a configuration block by the following

``` ruby
Mongoid::Geo.setup do |config|
  config.mongo_db_version = 1.8
  config.default_units = :miles #set your default units and distance returned will be displayed in those units 
  config.distance_formula = :spherical #other option is flat for distance calculation if on 1.7
end
```
- Haversine has been refactored using the distance formula found in Geokit
- Removed Geo & am now using autoload the modules into Mongoid::Geo
- Separated Model & Models Module outside of Near for cleanup

I need some help more time to get the test app cleaned up and somewhere very maintainable. Any help is appreciated. I really need this gem so I'll be working on it as much as possible.

### CODE REVIEW

**Comment by salbito** [comment]
I know its a lot of changes but I figured it would be best to get all of these up there before the amount of commits gets out of hand.

**Comment by kristianmandrup** [comment]
TRULY AWESOME!!!!!

I will be happy to let you continue with this gem if you like. I have moved my efforts to other supporting geo gems, like geo_calc and geo_vectors. I'm trying to build a small suite that work together to provide nice solutions for most of the geo use cases on the server side. The geo suite should also play nice with geocoder. 
Not sure how geokit fits into this. Last time I checked it seemed very A.R minded?

**Comment by salbito** [comment]
I'm still trying to really get grips on the gem as a whole and have been coming up with some weird issues. Maybe after some more changes, time, and really getting down to the nitty gritty of things I can help out a lot more. @ryanong maybe if you have time instead of working on the 1.9.2 of define_singleton_method issue we could put our heads together and really make this gem easily extensible.

**Comment by ryanong** [comment]
salbito, yea I am on irc all the time.
just hit me up as ryanisateapot on freenode
You might want to checkout the refactor I made. It seems like we did a lot of the same stuff.

**Comment by ryanong** [comment]
Here are my comments.
- Like the new setup method. But I am not sure if it is entirely necessary, we might want to look into piggy backing of the mongoid.yml config. Keeping all the configs in one area would be really nice.
- Good idea with the Haversine refactor will pull asap
- Why is autoload preferred over require? I haven't used it that often.

Also I removed to_models, and to_model entirely. They were really inefficient to begin with. I will most likely make a new geoNear module that allows for where chaining beforehand.

**Comment by salbito** [comment]
I will look into the mongoid.yml config. My only concern is relying on Mongoid configuration methods not to change but looking at where is the work is going on Mongoid it appears that won't be much of an issue. I use autoload as its a practice common to me. Just to let you know I do have a branch called ryanong_merge which is a merge of all of your work with my restructuring on top. Take a look and maybe that may be more adventurous for us to pull up rather then my current master branch pull request.

https://github.com/salbito/mongoid-geo/tree/ryanong_merge

**Comment by salbito** [comment]
I'm going to close this as I work on getting a branch that has both of our stuff merged together in a working fashion.

**Comment by kristianmandrup** [comment]
Cool :) Looking forward to see the results!

**Pull request closed without merging**
