### PR TITLE
Mongo 18 spherical

### PR DESCRIPTION
**Pull request by niedhui**
Now I can run 
  rspec spec/mongoid/
and it seem to work now on my local. please try again .
and thanks for fefactoring my rspec file .
Thanks

### CODE REVIEW

**Comment by kristianmandrup** [comment]
I just checked out your latest branch and these are the results in my configuration/environment:

$ mongo
MongoDB shell version: 1.8.1

$ rspec spec/mongoid/db_v1_8/spherical_calc_spec.rb

Mongoid Spherical geonear distance calculations
  Normal mode distance
    Mongo DB < 1.7
distances: [0.0, 1.8062052078680642]
      calculate distance
    Mongo DB 1.8
distances: [0.0, 120.82877478220875]
      calculate distance wrong since not using spherical mode with Mongo 1.8
  Spherical mode distance
    Mongo DB < 1.7
distances: [0.0, 2.10359400986274]
      calculate distance
    Mongo DB 1.8
distances: [0.0, 120.82877478220875]
      calculates distance (FAILED - 1)

The distances of 120.82877478220875 when using Mongo 1.8 internal distance algorithm is way off! 
Also strange that the distance of 2.10359400986274 is calculated when using spherical mode, which should fix the bug mentioned previously, that lat/lng in the location array should be reversed for spherical calculations.
The distance 1.8062052078680642 is correctly calculated only for normal mode.
Also the 120 result is achieved by Mongo DB for both normal and spherical mode!?

Comments!?

**Comment by niedhui** [comment]
here is mine:
[~/workspace/ruby/mongoid-geo](mongo_18_spherical) $ mongo
MongoDB shell version: 1.8.1
connecting to: test

> db.version()
> 1.8.1
> exit
> bye
> [~/workspace/ruby/mongoid-geo](mongo_18_spherical) $ rspec spec/mongoid/db_v1_8/spherical_calc_spec.rb 

Mongoid Spherical geonear distance calculations
  Normal mode distance
    Mongo DB < 1.7
distances: [0.0, 1.8062052078680642]
      calculate distance
    Mongo DB 1.8
distances: [0.0, 120.82877478220875]
      calculate distance wrong since not using spherical mode with Mongo 1.8
  Spherical mode distance
    Mongo DB < 1.7
distances: [0.0, 2.10359400986274]
      calculate distance
    Mongo DB 1.8
distances: [0.0, 1.8061253521165859]
      calculates distance

Finished in 0.077 seconds
4 examples, 0 failures

I think when specify Mongoid::Geo.mongo_db_version = 1.6 , the result is calculate by Haversine internal,so it's ok.
when  Mongoid::Geo.mongo_db_version = 1.8
not using sphere mode,For lat/lng 1 radian is roughly 70 miles or 111.17 km,
db.runCommand({ geoNear : "points", near :[121.583509, 31.2010839]})
the result is  "dis" : 0.018965433178811608,
the multiplier should be 111.17,then the result is 2.1083872064884863
a little larger then sphere mode

I can only produce the problem you described when connected to a 1.6.x mongo server.
eg:Mongoid.configure.master = Mongo::Connection.new('192.168.1.215').db('mongoid-geo')
mongo 192.168.1.215
MongoDB shell version: 1.8.1
connecting to: 192.168.1.215/test

> db.version()
> 1.6.4

then the last spec is failed ....

Strange..

**Comment by kristianmandrup** [comment]
Thanks. I just added the radian multipliers you suggested for using Mongo DB 1.8. I now get the following output:
Mongoid Spherical geonear distance calculations
  Normal mode distance
    Mongo DB < 1.7
distances: [0.0, 1.8062052078680642]
      calculate distance
    Mongo DB 1.8
distances: [0.0, 2.1083872064884863]
      calculate distance
  Spherical mode distance
    Mongo DB < 1.7
distances: [0.0, 2.10359400986274]
      calculate distance
    Mongo DB 1.8
distances: [0.0, 2.1083872064884863]
      calculates distance

The changes have now been pushed to master and a new gem 0.4.3 released. Thanks!

**Comment by niedhui** [comment]
still can not figure out why yours is :
Mongo DB 1.8
distances: [0.0, 2.1083872064884863]

mine is 

Mongo DB 1.8
distances: [0.0, 1.8061253521165859]

and i think radian_multiplier may only applied to not spherical mode
and i'm a little confuing now..

oh my poor english ~~~~
sorry for occupying you so much time ....

**Comment by kristianmandrup** [comment]
Hey, its fine. We just need some others to try this out as well so we can get a stronger opinion on what the effects are in various environments. Your English is just fine ;) hehe.

I'm applying the #radian_multiplier for Mongo DB > =1.7 and only if the :unit option is used. Do you think I have to test for the mode (:spherical) as well here?

Cheers! And thanks for occupying my time on this to help resolve this issue!

**Comment by niedhui** [comment]
because now i run  spherical_calc_spec.rb ,the result is :
  Spherical mode distance
    Mongo DB < 1.7
distances: [0.0, 2.10359400986274]
      calculate distance
    Mongo DB 1.8
distances: [0.0, 0.03151576760238595]
      calculates distance (FAILED - 1)

change
134:        results = Address.geoNear @center.location, :location, :unit => :km, :mode => :sphere
to
134:        results = Address.geoNear @center.location, :location, :distanceMultiplier => 6371, :mode => :sphere
will be ok.

if not test mode ,i can only get the right distance 1.8061253521165859 kms with distanceMultiplier option when using spherical mode

and i think radian_multiplier is up to spherical mode , not mongo version. not quite sure

**Comment by kristianmandrup** [comment]
I just pushed a new refactoring fix with a Unit class to handle everything distance unit related ;)
It never worked for me using 6371 as the :distanceMultiplier option value when using Mongo 1.8.
I hope others can soon join the discussion with their ideas/experiences etc.

**Pull request merged**
